### ISSUE TITLE
Question about hidden input fields

### ISSUE THREAD

**Issue by diogo-almeida** [addrummond/ibex#11]
Hi Alex! I am trying to incorporate Ibex into a streamlined pipeline such that some students can work with it, and I am running into a small problem: Apparently, data input on a regular input field is saved, but the same data input in a hidden input field is not. In other words, changing the 'type' attribute from "text" to "hidden" prevents the logging of the data.

I am trying to parse a query string into a unique identifier such that I can cross reference the data collected in Qualtrics and Ibex without any participant intervention: Participants visit the Qualtrics webpage, fill their forms etc, and then are automatically redirected to an Ibex experiment with randomly generated code as a unique identifier in a query string (something like "url?SUBJECTCODE"). On my instructions page I would just extract the query string with a simple javascript snippet, but I need to log this information to the results file. Everything works fine if I display the parsed string in a text input and have the participant hit the "continue" link, but that creates the risk that participants edit the information. When the very same input field is set to hidden to prevent this, however, the data is not logged.

Any ideas about why that is? Is there a simpler way of logging data hidden from the participants that I should be trying?

**Comment by tmalsburg** [comment]
The solution below is a bit of a hack but I used this in several experiments and it worked well.  The idea is basically to store the survey code using a DashedSentence controller that is displayed for just 1 ms:

Parse the query string using the code below:

``` Javascript
var QueryString = function () {
  var query_string = {};
  var query = window.location.search.substring(1);
  var vars = query.split("&");
  for (var i=0;i<vars.length;i++) {
    var pair = vars[i].split("=");
        // If first entry with this name
    if (typeof query_string[pair[0]] === "undefined") {
      query_string[pair[0]] = pair[1];
        // If second entry with this name
    } else if (typeof query_string[pair[0]] === "string") {
      var arr = [ query_string[pair[0]], pair[1] ];
      query_string[pair[0]] = arr;
        // If third or later entry with this name
    } else {
      query_string[pair[0]].push(pair[1]);
    }
  } 
    return query_string;
} ();
```

Add the `DashedSentence` controller to the items list:

``` Javascript
var items = [
    ["surveycode", "DashedSentence", {s:"" + QueryString.surveycode, mode:"speeded acceptability", wordTime:1}],
...
```

Make sure the "surveycode" item is included in the `shuffleSequence`:

``` Javascript
var shuffleSequence = seq("surveycode", ...
```
