### ISSUE TITLE
Last word in DashedSentence trial can receive reading time None.

### ISSUE THREAD

**Issue by tmalsburg** [addrummond/ibex#18]
It doesn't happen often but when it happens it's always on the last word of a trial.  Not sure what information could be useful to debug this.

**Comment by leaena-essl** [comment]
This is also happening to me.

**Comment by addrummond** [comment]
Possibly fixed by https://github.com/addrummond/ibex/commit/6111fcce7422cba3e4b5b091842b360d1f429012, if this was a result of occasional use of the 'next' button on iPhones/iPads.
