### ISSUE TITLE
Latin Square looks at everything in items declaration, not just items in running order

### ISSUE THREAD

**Issue by vboyce** [addrummond/ibex#21]
(It's unclear to me whether this behavior needs to be fixed, or just needs to be clearly documented.)

When using a Latin Square set up, if you have Latin square elements in the items list which are not in the running list, these appear to be used when selecting the Latin square item/group combos, but then not (of course) not displayed. This leads to fewer items being displayed than expected. 

Sample code that shows this problem:

var shuffleSequence = seq(randomize(anyOf("a", "b")));
var showProgressBar = false;

var items = [
 [["a", "1"], "Message", {html:'a 1'}],
 [["a", "2"], "Message", {html:'a 2'}],
 [["a", "3"], "Message", {html:'a 3'}],
 [["a", "4"], "Message", {html:'a 4'}],
 [["b", "1"], "Message", {html:'b 1'}],
 [["b", "2"], "Message", {html:'b 2'}],
 [["b", "3"], "Message", {html:'b 3'}],
 [["b", "4"], "Message", {html:'b 4'}],
 [["c", "1"], "Message", {html:'c 1'}],
 [["c", "2"], "Message", {html:'c 2'}],
 [["c", "3"], "Message", {html:'c 3'}],
 [["c", "4"], "Message", {html:'c 4'}],
 [["d", "1"], "Message", {html:'d 1'}],
 [["d", "2"], "Message", {html:'d 2'}],
 [["d", "3"], "Message", {html:'d 3'}],
 [["d", "4"], "Message", {html:'d 4'}],
];

The desired behavior would be for it to show 4 things, one from each of 1-4, in either a or b variety. However, the actual behavior is to show 2 things, one a and one b. (When the lines with c and d labels are removed, it behaves as desired. )

**Comment by addrummond** [comment]
This is the intended behavior, for whatever that's worth. As there may be any amount of existing code that implicitly depends on this behavior, changing it is probably not advisable.

I would be happy to accept pull requests to the documentation making this more clear.
