### ISSUE TITLE
Warning: Have you used _SetCounter_twice

### ISSUE THREAD

**Issue by SheCodes7** [addrummond/ibex#27]
Hello, 
For some reason I get this warning towards the end of my experiment.
I'm sure that I did not use _SetCounter_ twice in my code, only once.

![set_counter_error](https://user-images.githubusercontent.com/9379429/122127984-a6fead00-ce3c-11eb-8d77-f9a41795c0e9.png)

Does anyone know what this is all about and how I can solve this?

Thank you for your attention, looking forward to a reply.

**Comment by addrummond** [comment]
Could you please provide a data file that gives rise to this error.

**Comment by SheCodes7** [comment]
Here it is:
[example_data.txt](https://github.com/addrummond/ibex/files/6659235/example_data.txt)

And this is the link to the experiment:
https://ibex.spellout.net/experiments/nofi/AgreementUAC/view

You can take it if you want (just write 1 in all the input boxes)

Thank you!

**Comment by addrummond** [comment]
It's probably the use of `startsWith("s")` in your shuffle sequence. That will include `"setcounter"`, so the `__SetCounter__` controller will be included at multiple points in your running order. You should be able to fix it by changing `"setcounter"` to a string that doesn't start with `s` or `F`.

**Comment by SheCodes7** [comment]
Oh Wow! I would have never thought about it!
Thank you so much, have a great day.
